### ISSUE TITLE
Condor scan client fails on HTChirp exception

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#186]
Since 3.10, trying to run the scanner (manually) on condor results in the client failing with the following exception from HTChirp:
```
2023-05-05 04:42:40 gpub069.delta.ncsa.illinois.edu skyscan.client[20] INFO Starting up a Skymap Scanner client for event: startup_json_dict['mq_basename']='35405932-1:12-1683279043'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ewms_pilot/utils.py", line 70, in wrapper
    _initial_chirp()
  File "/usr/local/lib/python3.10/dist-packages/ewms_pilot/utils.py", line 33, in _initial_chirp
    chirp_status("")
  File "/usr/local/lib/python3.10/dist-packages/ewms_pilot/utils.py", line 24, in chirp_status
    LOGGER.info(f"chirping as '{c.whoami()}'")
  File "/usr/local/lib/python3.10/dist-packages/htchirp/htchirp.py", line 961, in whoami
    length = int(self._simple_command("whoami {0}\n".format(self.__class__.CHIRP_LINE_MAX)))
  File "/usr/local/lib/python3.10/dist-packages/htchirp/htchirp.py", line 212, in _simple_command
    return self._simple_response()
  File "/usr/local/lib/python3.10/dist-packages/htchirp/htchirp.py", line 242, in _simple_response
    self._check_response(int(response))
  File "/usr/local/lib/python3.10/dist-packages/htchirp/htchirp.py", line 275, in _check_response
    raise chirp_errors[response]
htchirp.htchirp.HTChirp.InvalidRequest: The form of the request is invalid.
```

Maybe this issue should be opened under `ewms-pilot` but I thought about reporting it here first.

**Comment by ric-evans** [comment]
Fixed by https://github.com/Observation-Management-Service/ewms-pilot/pull/31
